### ISSUE TITLE
Game-ending bug

### ISSUE THREAD

**Issue by Pwntagonist** [eliatlarge/FEMultiPlayer-V2#26]
Here's the error log:

java.lang.NullPointerException
	at net.fe.unit.Unit.move(Unit.java:148)
	at net.fe.overworldStage.ClientOverworldStage.processCommands(ClientOverworldStage.java:416)
	at net.fe.overworldStage.OverworldStage.beginStep(OverworldStage.java:184)
	at net.fe.overworldStage.ClientOverworldStage.beginStep(ClientOverworldStage.java:167)
	at net.fe.FEMultiplayer.loop(FEMultiplayer.java:263)
	at net.fe.FEMultiplayer.main(FEMultiplayer.java:77)

**Comment by eliatlarge** [comment]
can you reproduce it in a video, or give me a step by step description of what you were doing?

**Comment by eliatlarge** [comment]
no additional information provided, I can only presume this is an isolated incident.

**Comment by eliatlarge** [comment]
Pwn, if you haven't, try the PSA
