### ISSUE TITLE
[Fatal] Attempting to Summon a Phantom when there's no free adjacant spaces crashes game!

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#67]
Issue type: `problem`

#### Description:

Attempting to summon a Phantom when there's no available spaces to summon to crashes the game. The crash occurs after Summon is selected, when the cursor to select the desired spawn location would appear.

In other words, before the actual summon is even performed. Not only that, but on the opponent's end, it causes the summoner to despawn.

Man, I'm good at breaking shit. Gotta love Quality Assurance work. :-D

-------

#### Error Log:

    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at net.fe.overworldStage.context.Summon.updateCursor(Summon.java:157)
        at net.fe.overworldStage.context.Summon.startContext(Summon.java:53)
        at net.fe.overworldStage.context.UnitMoved.onSelect(UnitMoved.java:110)
        at net.fe.overworldStage.context.UnitMoved.onSelect(UnitMoved.java:24)
        at net.fe.overworldStage.MenuContext.onSelect(MenuContext.java:52)
        at net.fe.overworldStage.ClientOverworldStage.beginStep(ClientOverworldStage.java:277)
        at net.fe.FEMultiplayer.loop(FEMultiplayer.java:327)
        at net.fe.FEMultiplayer.main(FEMultiplayer.java:101)

-------

#### Examples:

Instructions for summoning were unfortunately too unclear for poor Ewan, causing him to tragically and hilariously despawn into another dimension of elder magic, or commit seppuku. riPepperonis Ewan, your disappearance into the netherworld will not be in vain. The below memorial pic is taken from the "opponent's" (*also me*) window as the game window for the summoner's team crashed.

![2016-04-26--190329_1600x900](https://cloud.githubusercontent.com/assets/18563664/14837010/c31eb6b4-0be2-11e6-92cc-532d4df0e6e4.png)

**Comment by SapphireTactician** [comment]
I downloaded a zip of Master not long ago, bug still persists. What's going on? The only changed I've observed was rescuing being restricted to mounts only. :-( Are these changes not available for download in Master yet?
