### ISSUE TITLE
[Fatal] Game crashes if Phantom moves / waits next to another unit

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#77]
Issue type: `problem`

#### Description:

Game crashes if Phantom moves (*or waits*) next to another unit, right before the Command Menu can appear. Mostly like because something related to Rescuing, Shoving / Smiting hasn't be implemented correctly for Phantoms.

-------

#### Error Log:

    java.lang.NullPointerException
        at net.fe.unit.Unit.get(Unit.java:955)
        at net.fe.unit.Unit.canRescue(Unit.java:282)
        at net.fe.overworldStage.context.UnitMoved.getCommands(UnitMoved.java:221)
        at net.fe.overworldStage.context.UnitMoved.<init>(UnitMoved.java:54)
        at net.fe.overworldStage.context.UnitSelected$1.execute(UnitSelected.java:81)
        at net.fe.unit.Unit.onStep(Unit.java:375)
        at net.fe.overworldStage.ClientOverworldStage.onStep(ClientOverworldStage.java:301)
        at net.fe.FEMultiplayer.loop(FEMultiplayer.java:336)
        at net.fe.FEMultiplayer.main(FEMultiplayer.java:101)

**Comment by eliatlarge** [comment]
I just recently merged ray's latest commit, which includes giving phantoms a con value. you may want to check out the latest version.

**Comment by SapphireTactician** [comment]
Can confirm bug still persists. What else can it be?
